/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_affiche (void);
GtkWidget* create_Ajout (void);
GtkWidget* create_suppression (void);
GtkWidget* create_modification (void);
GtkWidget* create_cptdef (void);
