/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_affiche (void)
{
  GtkWidget *affiche;
  AtkObject *atko;
  GtkWidget *fixed1;
  GtkWidget *treeview1;
  GtkWidget *entry1;
  GtkWidget *image13;
  GtkWidget *button1;
  GtkWidget *alignment2;
  GtkWidget *hbox2;
  GtkWidget *image2;
  GtkWidget *ajouter;
  GtkWidget *button2;
  GtkWidget *alignment3;
  GtkWidget *hbox3;
  GtkWidget *image3;
  GtkWidget *supprimer;
  GtkWidget *label1;
  GtkWidget *button_actu;
  GtkWidget *alignment14;
  GtkWidget *hbox14;
  GtkWidget *image15;
  GtkWidget *label39;
  GtkWidget *afficher;
  GtkWidget *button4;
  GtkWidget *recherche;
  GtkWidget *hbox1;
  GtkWidget *image1;
  GtkWidget *rech;
  GtkWidget *button3;
  GtkWidget *alignment4;
  GtkWidget *hbox4;
  GtkWidget *image4;
  GtkWidget *modifier;
  GtkWidget *cptdef;
  GtkWidget *alignment16;
  GtkWidget *hbox16;
  GtkWidget *image17;
  GtkWidget *label41;

  affiche = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (affiche), _("affiche"));

  fixed1 = gtk_fixed_new ();
  gtk_widget_show (fixed1);
  gtk_container_add (GTK_CONTAINER (affiche), fixed1);

  treeview1 = gtk_tree_view_new ();
  gtk_widget_show (treeview1);
  gtk_fixed_put (GTK_FIXED (fixed1), treeview1, 80, 128);
  gtk_widget_set_size_request (treeview1, 652, 448);

  entry1 = gtk_entry_new ();
  gtk_widget_show (entry1);
  gtk_fixed_put (GTK_FIXED (fixed1), entry1, 488, 608);
  gtk_widget_set_size_request (entry1, 160, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry1), 8226);

  image13 = create_pixmap (affiche, "index.jpeg");
  gtk_widget_show (image13);
  gtk_fixed_put (GTK_FIXED (fixed1), image13, 760, 264);
  gtk_widget_set_size_request (image13, 208, 224);
  gtk_misc_set_alignment (GTK_MISC (image13), 0.9, 0.9);

  button1 = gtk_button_new ();
  gtk_widget_show (button1);
  gtk_fixed_put (GTK_FIXED (fixed1), button1, 128, 608);
  gtk_widget_set_size_request (button1, 80, 32);

  alignment2 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment2);
  gtk_container_add (GTK_CONTAINER (button1), alignment2);

  hbox2 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox2);
  gtk_container_add (GTK_CONTAINER (alignment2), hbox2);

  image2 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image2);
  gtk_box_pack_start (GTK_BOX (hbox2), image2, FALSE, FALSE, 0);

  ajouter = gtk_label_new_with_mnemonic (_("Ajouter\n"));
  gtk_widget_show (ajouter);
  gtk_box_pack_start (GTK_BOX (hbox2), ajouter, FALSE, FALSE, 0);

  button2 = gtk_button_new ();
  gtk_widget_show (button2);
  gtk_fixed_put (GTK_FIXED (fixed1), button2, 216, 608);
  gtk_widget_set_size_request (button2, 104, 32);

  alignment3 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment3);
  gtk_container_add (GTK_CONTAINER (button2), alignment3);

  hbox3 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox3);
  gtk_container_add (GTK_CONTAINER (alignment3), hbox3);

  image3 = gtk_image_new_from_stock ("gtk-remove", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image3);
  gtk_box_pack_start (GTK_BOX (hbox3), image3, FALSE, FALSE, 0);

  supprimer = gtk_label_new_with_mnemonic (_("supprimer"));
  gtk_widget_show (supprimer);
  gtk_box_pack_start (GTK_BOX (hbox3), supprimer, FALSE, FALSE, 0);

  label1 = gtk_label_new (_("***Bienvenue dans l'espace technicien***"));
  gtk_widget_show (label1);
  gtk_fixed_put (GTK_FIXED (fixed1), label1, 280, 72);
  gtk_widget_set_size_request (label1, 289, 16);

  button_actu = gtk_button_new ();
  gtk_widget_show (button_actu);
  gtk_fixed_put (GTK_FIXED (fixed1), button_actu, 760, 176);
  gtk_widget_set_size_request (button_actu, 112, 32);

  alignment14 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment14);
  gtk_container_add (GTK_CONTAINER (button_actu), alignment14);

  hbox14 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox14);
  gtk_container_add (GTK_CONTAINER (alignment14), hbox14);

  image15 = gtk_image_new_from_stock ("gtk-refresh", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image15);
  gtk_box_pack_start (GTK_BOX (hbox14), image15, FALSE, FALSE, 0);

  label39 = gtk_label_new_with_mnemonic (_("Actualiser"));
  gtk_widget_show (label39);
  gtk_box_pack_start (GTK_BOX (hbox14), label39, FALSE, FALSE, 0);

  afficher = gtk_button_new_with_mnemonic (_("Afficher\n"));
  gtk_widget_show (afficher);
  gtk_fixed_put (GTK_FIXED (fixed1), afficher, 760, 136);
  gtk_widget_set_size_request (afficher, 74, 29);

  button4 = gtk_button_new ();
  gtk_widget_show (button4);
  gtk_fixed_put (GTK_FIXED (fixed1), button4, 648, 608);
  gtk_widget_set_size_request (button4, 56, 32);

  recherche = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (recherche);
  gtk_container_add (GTK_CONTAINER (button4), recherche);

  hbox1 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox1);
  gtk_container_add (GTK_CONTAINER (recherche), hbox1);

  image1 = gtk_image_new_from_stock ("gtk-find", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image1);
  gtk_box_pack_start (GTK_BOX (hbox1), image1, FALSE, FALSE, 0);

  rech = gtk_label_new_with_mnemonic ("");
  gtk_widget_show (rech);
  gtk_box_pack_start (GTK_BOX (hbox1), rech, FALSE, FALSE, 0);

  button3 = gtk_button_new ();
  gtk_widget_show (button3);
  gtk_fixed_put (GTK_FIXED (fixed1), button3, 336, 608);
  gtk_widget_set_size_request (button3, 96, 32);

  alignment4 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment4);
  gtk_container_add (GTK_CONTAINER (button3), alignment4);

  hbox4 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox4);
  gtk_container_add (GTK_CONTAINER (alignment4), hbox4);

  image4 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image4);
  gtk_box_pack_start (GTK_BOX (hbox4), image4, FALSE, FALSE, 0);

  modifier = gtk_label_new_with_mnemonic (_("modifier"));
  gtk_widget_show (modifier);
  gtk_box_pack_start (GTK_BOX (hbox4), modifier, FALSE, FALSE, 0);

  cptdef = gtk_button_new ();
  gtk_widget_show (cptdef);
  gtk_fixed_put (GTK_FIXED (fixed1), cptdef, 744, 512);
  gtk_widget_set_size_request (cptdef, 208, 37);

  alignment16 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment16);
  gtk_container_add (GTK_CONTAINER (cptdef), alignment16);

  hbox16 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox16);
  gtk_container_add (GTK_CONTAINER (alignment16), hbox16);

  image17 = gtk_image_new_from_stock ("gtk-preferences", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image17);
  gtk_box_pack_start (GTK_BOX (hbox16), image17, FALSE, FALSE, 0);

  label41 = gtk_label_new_with_mnemonic (_("Capteurs deffectueux"));
  gtk_widget_show (label41);
  gtk_box_pack_start (GTK_BOX (hbox16), label41, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) treeview1, "row_activated",
                    G_CALLBACK (on_treeview1_row_activated),
                    NULL);
  g_signal_connect ((gpointer) button1, "clicked",
                    G_CALLBACK (on_button1_clicked),
                    NULL);
  g_signal_connect ((gpointer) button2, "clicked",
                    G_CALLBACK (on_button2_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_actu, "clicked",
                    G_CALLBACK (on_button_actu_clicked),
                    NULL);
  g_signal_connect ((gpointer) afficher, "clicked",
                    G_CALLBACK (on_afficher_clicked),
                    NULL);
  g_signal_connect ((gpointer) button4, "clicked",
                    G_CALLBACK (on_button4_clicked),
                    NULL);
  g_signal_connect ((gpointer) button3, "clicked",
                    G_CALLBACK (on_button3_clicked),
                    NULL);
  g_signal_connect ((gpointer) cptdef, "clicked",
                    G_CALLBACK (on_cptdef_clicked),
                    NULL);

  atko = gtk_widget_get_accessible (affiche);
  atk_object_set_name (atko, _("affiche"));


  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (affiche, affiche, "affiche");
  GLADE_HOOKUP_OBJECT (affiche, fixed1, "fixed1");
  GLADE_HOOKUP_OBJECT (affiche, treeview1, "treeview1");
  GLADE_HOOKUP_OBJECT (affiche, entry1, "entry1");
  GLADE_HOOKUP_OBJECT (affiche, image13, "image13");
  GLADE_HOOKUP_OBJECT (affiche, button1, "button1");
  GLADE_HOOKUP_OBJECT (affiche, alignment2, "alignment2");
  GLADE_HOOKUP_OBJECT (affiche, hbox2, "hbox2");
  GLADE_HOOKUP_OBJECT (affiche, image2, "image2");
  GLADE_HOOKUP_OBJECT (affiche, ajouter, "ajouter");
  GLADE_HOOKUP_OBJECT (affiche, button2, "button2");
  GLADE_HOOKUP_OBJECT (affiche, alignment3, "alignment3");
  GLADE_HOOKUP_OBJECT (affiche, hbox3, "hbox3");
  GLADE_HOOKUP_OBJECT (affiche, image3, "image3");
  GLADE_HOOKUP_OBJECT (affiche, supprimer, "supprimer");
  GLADE_HOOKUP_OBJECT (affiche, label1, "label1");
  GLADE_HOOKUP_OBJECT (affiche, button_actu, "button_actu");
  GLADE_HOOKUP_OBJECT (affiche, alignment14, "alignment14");
  GLADE_HOOKUP_OBJECT (affiche, hbox14, "hbox14");
  GLADE_HOOKUP_OBJECT (affiche, image15, "image15");
  GLADE_HOOKUP_OBJECT (affiche, label39, "label39");
  GLADE_HOOKUP_OBJECT (affiche, afficher, "afficher");
  GLADE_HOOKUP_OBJECT (affiche, button4, "button4");
  GLADE_HOOKUP_OBJECT (affiche, recherche, "recherche");
  GLADE_HOOKUP_OBJECT (affiche, hbox1, "hbox1");
  GLADE_HOOKUP_OBJECT (affiche, image1, "image1");
  GLADE_HOOKUP_OBJECT (affiche, rech, "rech");
  GLADE_HOOKUP_OBJECT (affiche, button3, "button3");
  GLADE_HOOKUP_OBJECT (affiche, alignment4, "alignment4");
  GLADE_HOOKUP_OBJECT (affiche, hbox4, "hbox4");
  GLADE_HOOKUP_OBJECT (affiche, image4, "image4");
  GLADE_HOOKUP_OBJECT (affiche, modifier, "modifier");
  GLADE_HOOKUP_OBJECT (affiche, cptdef, "cptdef");
  GLADE_HOOKUP_OBJECT (affiche, alignment16, "alignment16");
  GLADE_HOOKUP_OBJECT (affiche, hbox16, "hbox16");
  GLADE_HOOKUP_OBJECT (affiche, image17, "image17");
  GLADE_HOOKUP_OBJECT (affiche, label41, "label41");

  return affiche;
}

GtkWidget*
create_Ajout (void)
{
  GtkWidget *Ajout;
  GtkWidget *fixed2;
  GtkWidget *entry3;
  GtkWidget *entry4;
  GtkWidget *id;
  GtkWidget *radio2;
  GSList *radio2_group = NULL;
  GtkWidget *label_valeur;
  GtkWidget *entry_type;
  GtkWidget *checkbutton2;
  GtkWidget *checkbutton1;
  GtkWidget *label_etat;
  GtkWidget *radio1;
  GtkWidget *valid_ajout;
  GtkWidget *alignment5;
  GtkWidget *hbox5;
  GtkWidget *image5;
  GtkWidget *label13;
  GtkWidget *etage;
  GtkObject *spin_etage_adj;
  GtkWidget *spin_etage;
  GtkWidget *retour1;
  GtkWidget *alignment6;
  GtkWidget *hbox6;
  GtkWidget *image6;
  GtkWidget *label14;

  Ajout = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (Ajout), _("Ajout"));

  fixed2 = gtk_fixed_new ();
  gtk_widget_show (fixed2);
  gtk_container_add (GTK_CONTAINER (Ajout), fixed2);

  entry3 = gtk_entry_new ();
  gtk_widget_show (entry3);
  gtk_fixed_put (GTK_FIXED (fixed2), entry3, 208, 56);
  gtk_widget_set_size_request (entry3, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry3), 8226);

  entry4 = gtk_entry_new ();
  gtk_widget_show (entry4);
  gtk_fixed_put (GTK_FIXED (fixed2), entry4, 168, 256);
  gtk_widget_set_size_request (entry4, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry4), 8226);

  id = gtk_label_new (_("Donner l'ID :"));
  gtk_widget_show (id);
  gtk_fixed_put (GTK_FIXED (fixed2), id, 56, 64);
  gtk_widget_set_size_request (id, 104, 16);

  radio2 = gtk_radio_button_new_with_mnemonic (NULL, _("passif"));
  gtk_widget_show (radio2);
  gtk_fixed_put (GTK_FIXED (fixed2), radio2, 336, 128);
  gtk_widget_set_size_request (radio2, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radio2), radio2_group);
  radio2_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radio2));

  label_valeur = gtk_label_new (_("valeur :"));
  gtk_widget_show (label_valeur);
  gtk_fixed_put (GTK_FIXED (fixed2), label_valeur, 72, 264);
  gtk_widget_set_size_request (label_valeur, 64, 16);

  entry_type = gtk_label_new (_("De type :"));
  gtk_widget_show (entry_type);
  gtk_fixed_put (GTK_FIXED (fixed2), entry_type, 56, 128);
  gtk_widget_set_size_request (entry_type, 80, 24);

  checkbutton2 = gtk_check_button_new_with_mnemonic (_("Defectueux"));
  gtk_widget_show (checkbutton2);
  gtk_fixed_put (GTK_FIXED (fixed2), checkbutton2, 336, 192);
  gtk_widget_set_size_request (checkbutton2, 118, 24);

  checkbutton1 = gtk_check_button_new_with_mnemonic (_("Bonne"));
  gtk_widget_show (checkbutton1);
  gtk_fixed_put (GTK_FIXED (fixed2), checkbutton1, 168, 192);
  gtk_widget_set_size_request (checkbutton1, 118, 24);

  label_etat = gtk_label_new (_("Etat :"));
  gtk_widget_show (label_etat);
  gtk_fixed_put (GTK_FIXED (fixed2), label_etat, 72, 192);
  gtk_widget_set_size_request (label_etat, 49, 17);

  radio1 = gtk_radio_button_new_with_mnemonic (NULL, _("actif"));
  gtk_widget_show (radio1);
  gtk_fixed_put (GTK_FIXED (fixed2), radio1, 176, 128);
  gtk_widget_set_size_request (radio1, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radio1), radio2_group);
  radio2_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radio1));

  valid_ajout = gtk_button_new ();
  gtk_widget_show (valid_ajout);
  gtk_fixed_put (GTK_FIXED (fixed2), valid_ajout, 80, 368);
  gtk_widget_set_size_request (valid_ajout, 80, 32);

  alignment5 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment5);
  gtk_container_add (GTK_CONTAINER (valid_ajout), alignment5);

  hbox5 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox5);
  gtk_container_add (GTK_CONTAINER (alignment5), hbox5);

  image5 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image5);
  gtk_box_pack_start (GTK_BOX (hbox5), image5, FALSE, FALSE, 0);

  label13 = gtk_label_new_with_mnemonic (_("valider"));
  gtk_widget_show (label13);
  gtk_box_pack_start (GTK_BOX (hbox5), label13, FALSE, FALSE, 0);

  etage = gtk_label_new (_("Etage:"));
  gtk_widget_show (etage);
  gtk_fixed_put (GTK_FIXED (fixed2), etage, 80, 312);
  gtk_widget_set_size_request (etage, 49, 17);

  spin_etage_adj = gtk_adjustment_new (1, 0, 4, 1, 10, 10);
  spin_etage = gtk_spin_button_new (GTK_ADJUSTMENT (spin_etage_adj), 1, 0);
  gtk_widget_show (spin_etage);
  gtk_fixed_put (GTK_FIXED (fixed2), spin_etage, 136, 312);
  gtk_widget_set_size_request (spin_etage, 60, 27);

  retour1 = gtk_button_new ();
  gtk_widget_show (retour1);
  gtk_fixed_put (GTK_FIXED (fixed2), retour1, 192, 368);
  gtk_widget_set_size_request (retour1, 80, 32);

  alignment6 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment6);
  gtk_container_add (GTK_CONTAINER (retour1), alignment6);

  hbox6 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox6);
  gtk_container_add (GTK_CONTAINER (alignment6), hbox6);

  image6 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image6);
  gtk_box_pack_start (GTK_BOX (hbox6), image6, FALSE, FALSE, 0);

  label14 = gtk_label_new_with_mnemonic (_("Retour"));
  gtk_widget_show (label14);
  gtk_box_pack_start (GTK_BOX (hbox6), label14, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) radio2, "toggled",
                    G_CALLBACK (on_radio2_toggled),
                    NULL);
  g_signal_connect ((gpointer) checkbutton2, "toggled",
                    G_CALLBACK (on_checkbutton2_toggled),
                    NULL);
  g_signal_connect ((gpointer) checkbutton1, "toggled",
                    G_CALLBACK (on_checkbutton1_toggled),
                    NULL);
  g_signal_connect ((gpointer) radio1, "toggled",
                    G_CALLBACK (on_radio1_toggled),
                    NULL);
  g_signal_connect ((gpointer) valid_ajout, "clicked",
                    G_CALLBACK (on_button5_clicked),
                    NULL);
  g_signal_connect ((gpointer) retour1, "clicked",
                    G_CALLBACK (on_button6_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Ajout, Ajout, "Ajout");
  GLADE_HOOKUP_OBJECT (Ajout, fixed2, "fixed2");
  GLADE_HOOKUP_OBJECT (Ajout, entry3, "entry3");
  GLADE_HOOKUP_OBJECT (Ajout, entry4, "entry4");
  GLADE_HOOKUP_OBJECT (Ajout, id, "id");
  GLADE_HOOKUP_OBJECT (Ajout, radio2, "radio2");
  GLADE_HOOKUP_OBJECT (Ajout, label_valeur, "label_valeur");
  GLADE_HOOKUP_OBJECT (Ajout, entry_type, "entry_type");
  GLADE_HOOKUP_OBJECT (Ajout, checkbutton2, "checkbutton2");
  GLADE_HOOKUP_OBJECT (Ajout, checkbutton1, "checkbutton1");
  GLADE_HOOKUP_OBJECT (Ajout, label_etat, "label_etat");
  GLADE_HOOKUP_OBJECT (Ajout, radio1, "radio1");
  GLADE_HOOKUP_OBJECT (Ajout, valid_ajout, "valid_ajout");
  GLADE_HOOKUP_OBJECT (Ajout, alignment5, "alignment5");
  GLADE_HOOKUP_OBJECT (Ajout, hbox5, "hbox5");
  GLADE_HOOKUP_OBJECT (Ajout, image5, "image5");
  GLADE_HOOKUP_OBJECT (Ajout, label13, "label13");
  GLADE_HOOKUP_OBJECT (Ajout, etage, "etage");
  GLADE_HOOKUP_OBJECT (Ajout, spin_etage, "spin_etage");
  GLADE_HOOKUP_OBJECT (Ajout, retour1, "retour1");
  GLADE_HOOKUP_OBJECT (Ajout, alignment6, "alignment6");
  GLADE_HOOKUP_OBJECT (Ajout, hbox6, "hbox6");
  GLADE_HOOKUP_OBJECT (Ajout, image6, "image6");
  GLADE_HOOKUP_OBJECT (Ajout, label14, "label14");

  return Ajout;
}

GtkWidget*
create_suppression (void)
{
  GtkWidget *suppression;
  GtkWidget *fixed3;
  GtkWidget *entry5;
  GtkWidget *label_suppr;
  GtkWidget *valid_supp;
  GtkWidget *alignment7;
  GtkWidget *hbox7;
  GtkWidget *image7;
  GtkWidget *label16;
  GtkWidget *supprimer;
  GtkWidget *alignment8;
  GtkWidget *hbox8;
  GtkWidget *image8;
  GtkWidget *label17;
  GtkWidget *retour_supp;
  GtkWidget *alignment9;
  GtkWidget *hbox9;
  GtkWidget *image9;
  GtkWidget *label18;

  suppression = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (suppression), _("supprission"));

  fixed3 = gtk_fixed_new ();
  gtk_widget_show (fixed3);
  gtk_container_add (GTK_CONTAINER (suppression), fixed3);

  entry5 = gtk_entry_new ();
  gtk_widget_show (entry5);
  gtk_fixed_put (GTK_FIXED (fixed3), entry5, 288, 72);
  gtk_widget_set_size_request (entry5, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry5), 8226);

  label_suppr = gtk_label_new (_("Donner l'id du capteur a supprimer:"));
  gtk_widget_show (label_suppr);
  gtk_fixed_put (GTK_FIXED (fixed3), label_suppr, 24, 72);
  gtk_widget_set_size_request (label_suppr, 256, 24);

  valid_supp = gtk_button_new ();
  gtk_widget_show (valid_supp);
  gtk_fixed_put (GTK_FIXED (fixed3), valid_supp, 488, 72);
  gtk_widget_set_size_request (valid_supp, 80, 24);

  alignment7 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment7);
  gtk_container_add (GTK_CONTAINER (valid_supp), alignment7);

  hbox7 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox7);
  gtk_container_add (GTK_CONTAINER (alignment7), hbox7);

  image7 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image7);
  gtk_box_pack_start (GTK_BOX (hbox7), image7, FALSE, FALSE, 0);

  label16 = gtk_label_new_with_mnemonic (_("valider"));
  gtk_widget_show (label16);
  gtk_box_pack_start (GTK_BOX (hbox7), label16, FALSE, FALSE, 0);

  supprimer = gtk_button_new ();
  gtk_widget_show (supprimer);
  gtk_fixed_put (GTK_FIXED (fixed3), supprimer, 56, 184);
  gtk_widget_set_size_request (supprimer, 106, 32);

  alignment8 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment8);
  gtk_container_add (GTK_CONTAINER (supprimer), alignment8);

  hbox8 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox8);
  gtk_container_add (GTK_CONTAINER (alignment8), hbox8);

  image8 = gtk_image_new_from_stock ("gtk-remove", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image8);
  gtk_box_pack_start (GTK_BOX (hbox8), image8, FALSE, FALSE, 0);

  label17 = gtk_label_new_with_mnemonic (_("supprimer"));
  gtk_widget_show (label17);
  gtk_box_pack_start (GTK_BOX (hbox8), label17, FALSE, FALSE, 0);

  retour_supp = gtk_button_new ();
  gtk_widget_show (retour_supp);
  gtk_fixed_put (GTK_FIXED (fixed3), retour_supp, 184, 184);
  gtk_widget_set_size_request (retour_supp, 82, 32);

  alignment9 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment9);
  gtk_container_add (GTK_CONTAINER (retour_supp), alignment9);

  hbox9 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox9);
  gtk_container_add (GTK_CONTAINER (alignment9), hbox9);

  image9 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image9);
  gtk_box_pack_start (GTK_BOX (hbox9), image9, FALSE, FALSE, 0);

  label18 = gtk_label_new_with_mnemonic (_("Retour"));
  gtk_widget_show (label18);
  gtk_box_pack_start (GTK_BOX (hbox9), label18, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) valid_supp, "clicked",
                    G_CALLBACK (on_button7_clicked),
                    NULL);
  g_signal_connect ((gpointer) supprimer, "clicked",
                    G_CALLBACK (on_button8_clicked),
                    NULL);
  g_signal_connect ((gpointer) retour_supp, "clicked",
                    G_CALLBACK (on_button9_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (suppression, suppression, "suppression");
  GLADE_HOOKUP_OBJECT (suppression, fixed3, "fixed3");
  GLADE_HOOKUP_OBJECT (suppression, entry5, "entry5");
  GLADE_HOOKUP_OBJECT (suppression, label_suppr, "label_suppr");
  GLADE_HOOKUP_OBJECT (suppression, valid_supp, "valid_supp");
  GLADE_HOOKUP_OBJECT (suppression, alignment7, "alignment7");
  GLADE_HOOKUP_OBJECT (suppression, hbox7, "hbox7");
  GLADE_HOOKUP_OBJECT (suppression, image7, "image7");
  GLADE_HOOKUP_OBJECT (suppression, label16, "label16");
  GLADE_HOOKUP_OBJECT (suppression, supprimer, "supprimer");
  GLADE_HOOKUP_OBJECT (suppression, alignment8, "alignment8");
  GLADE_HOOKUP_OBJECT (suppression, hbox8, "hbox8");
  GLADE_HOOKUP_OBJECT (suppression, image8, "image8");
  GLADE_HOOKUP_OBJECT (suppression, label17, "label17");
  GLADE_HOOKUP_OBJECT (suppression, retour_supp, "retour_supp");
  GLADE_HOOKUP_OBJECT (suppression, alignment9, "alignment9");
  GLADE_HOOKUP_OBJECT (suppression, hbox9, "hbox9");
  GLADE_HOOKUP_OBJECT (suppression, image9, "image9");
  GLADE_HOOKUP_OBJECT (suppression, label18, "label18");

  return suppression;
}

GtkWidget*
create_modification (void)
{
  GtkWidget *modification;
  GtkWidget *fixed4;
  GtkWidget *entry6;
  GtkWidget *entry7;
  GtkWidget *entry8;
  GtkWidget *label19;
  GtkWidget *label20;
  GtkWidget *label21;
  GtkWidget *label22;
  GtkWidget *label26;
  GtkWidget *valid_modif;
  GtkWidget *alignment10;
  GtkWidget *hbox10;
  GtkWidget *image10;
  GtkWidget *label23;
  GtkWidget *modifier;
  GtkWidget *alignment11;
  GtkWidget *hbox11;
  GtkWidget *image11;
  GtkWidget *label24;
  GtkWidget *radiobutton4;
  GSList *radiobutton4_group = NULL;
  GtkWidget *radiobutton5;
  GtkWidget *checkbutton4;
  GtkWidget *checkbutton3;
  GtkWidget *retour_modif;
  GtkWidget *alignment12;
  GtkWidget *hbox12;
  GtkWidget *image12;
  GtkWidget *label25;

  modification = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (modification), _("modification"));

  fixed4 = gtk_fixed_new ();
  gtk_widget_show (fixed4);
  gtk_container_add (GTK_CONTAINER (modification), fixed4);

  entry6 = gtk_entry_new ();
  gtk_widget_show (entry6);
  gtk_fixed_put (GTK_FIXED (fixed4), entry6, 320, 32);
  gtk_widget_set_size_request (entry6, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry6), 8226);

  entry7 = gtk_entry_new ();
  gtk_widget_show (entry7);
  gtk_fixed_put (GTK_FIXED (fixed4), entry7, 200, 96);
  gtk_widget_set_size_request (entry7, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry7), 8226);

  entry8 = gtk_entry_new ();
  gtk_widget_show (entry8);
  gtk_fixed_put (GTK_FIXED (fixed4), entry8, 152, 264);
  gtk_widget_set_size_request (entry8, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry8), 8226);

  label19 = gtk_label_new (_("Donner l'ID du capteur a modifier:"));
  gtk_widget_show (label19);
  gtk_fixed_put (GTK_FIXED (fixed4), label19, 64, 40);
  gtk_widget_set_size_request (label19, 224, 16);

  label20 = gtk_label_new (_("Nouveau ID:"));
  gtk_widget_show (label20);
  gtk_fixed_put (GTK_FIXED (fixed4), label20, 56, 104);
  gtk_widget_set_size_request (label20, 104, 16);

  label21 = gtk_label_new (_("Type"));
  gtk_widget_show (label21);
  gtk_fixed_put (GTK_FIXED (fixed4), label21, 48, 176);
  gtk_widget_set_size_request (label21, 80, 16);

  label22 = gtk_label_new (_("valeur"));
  gtk_widget_show (label22);
  gtk_fixed_put (GTK_FIXED (fixed4), label22, 56, 272);
  gtk_widget_set_size_request (label22, 72, 16);

  label26 = gtk_label_new (_("Etat :"));
  gtk_widget_show (label26);
  gtk_fixed_put (GTK_FIXED (fixed4), label26, 72, 216);
  gtk_widget_set_size_request (label26, 49, 17);

  valid_modif = gtk_button_new ();
  gtk_widget_show (valid_modif);
  gtk_fixed_put (GTK_FIXED (fixed4), valid_modif, 512, 32);
  gtk_widget_set_size_request (valid_modif, 88, 32);

  alignment10 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment10);
  gtk_container_add (GTK_CONTAINER (valid_modif), alignment10);

  hbox10 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox10);
  gtk_container_add (GTK_CONTAINER (alignment10), hbox10);

  image10 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image10);
  gtk_box_pack_start (GTK_BOX (hbox10), image10, FALSE, FALSE, 0);

  label23 = gtk_label_new_with_mnemonic (_("Valider"));
  gtk_widget_show (label23);
  gtk_box_pack_start (GTK_BOX (hbox10), label23, FALSE, FALSE, 0);

  modifier = gtk_button_new ();
  gtk_widget_show (modifier);
  gtk_fixed_put (GTK_FIXED (fixed4), modifier, 88, 336);
  gtk_widget_set_size_request (modifier, 96, 32);

  alignment11 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment11);
  gtk_container_add (GTK_CONTAINER (modifier), alignment11);

  hbox11 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox11);
  gtk_container_add (GTK_CONTAINER (alignment11), hbox11);

  image11 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image11);
  gtk_box_pack_start (GTK_BOX (hbox11), image11, FALSE, FALSE, 0);

  label24 = gtk_label_new_with_mnemonic (_("modifier"));
  gtk_widget_show (label24);
  gtk_box_pack_start (GTK_BOX (hbox11), label24, FALSE, FALSE, 0);

  radiobutton4 = gtk_radio_button_new_with_mnemonic (NULL, _("Actif"));
  gtk_widget_show (radiobutton4);
  gtk_fixed_put (GTK_FIXED (fixed4), radiobutton4, 160, 168);
  gtk_widget_set_size_request (radiobutton4, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton4), radiobutton4_group);
  radiobutton4_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton4));

  radiobutton5 = gtk_radio_button_new_with_mnemonic (NULL, _("Passif"));
  gtk_widget_show (radiobutton5);
  gtk_fixed_put (GTK_FIXED (fixed4), radiobutton5, 328, 168);
  gtk_widget_set_size_request (radiobutton5, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton5), radiobutton4_group);
  radiobutton4_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton5));

  checkbutton4 = gtk_check_button_new_with_mnemonic (_("Defectueux"));
  gtk_widget_show (checkbutton4);
  gtk_fixed_put (GTK_FIXED (fixed4), checkbutton4, 352, 216);
  gtk_widget_set_size_request (checkbutton4, 118, 24);

  checkbutton3 = gtk_check_button_new_with_mnemonic (_("Bonne"));
  gtk_widget_show (checkbutton3);
  gtk_fixed_put (GTK_FIXED (fixed4), checkbutton3, 168, 216);
  gtk_widget_set_size_request (checkbutton3, 118, 24);

  retour_modif = gtk_button_new ();
  gtk_widget_show (retour_modif);
  gtk_fixed_put (GTK_FIXED (fixed4), retour_modif, 224, 336);
  gtk_widget_set_size_request (retour_modif, 88, 32);

  alignment12 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment12);
  gtk_container_add (GTK_CONTAINER (retour_modif), alignment12);

  hbox12 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox12);
  gtk_container_add (GTK_CONTAINER (alignment12), hbox12);

  image12 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image12);
  gtk_box_pack_start (GTK_BOX (hbox12), image12, FALSE, FALSE, 0);

  label25 = gtk_label_new_with_mnemonic (_("Retour"));
  gtk_widget_show (label25);
  gtk_box_pack_start (GTK_BOX (hbox12), label25, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) valid_modif, "clicked",
                    G_CALLBACK (on_button10_clicked),
                    NULL);
  g_signal_connect ((gpointer) modifier, "clicked",
                    G_CALLBACK (on_button11_clicked),
                    NULL);
  g_signal_connect ((gpointer) radiobutton4, "toggled",
                    G_CALLBACK (on_radiobutton4_toggled),
                    NULL);
  g_signal_connect ((gpointer) radiobutton5, "toggled",
                    G_CALLBACK (on_radiobutton5_toggled),
                    NULL);
  g_signal_connect ((gpointer) checkbutton4, "toggled",
                    G_CALLBACK (on_checkbutton4_toggled),
                    NULL);
  g_signal_connect ((gpointer) checkbutton3, "toggled",
                    G_CALLBACK (on_checkbutton3_toggled),
                    NULL);
  g_signal_connect ((gpointer) retour_modif, "clicked",
                    G_CALLBACK (on_button12_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (modification, modification, "modification");
  GLADE_HOOKUP_OBJECT (modification, fixed4, "fixed4");
  GLADE_HOOKUP_OBJECT (modification, entry6, "entry6");
  GLADE_HOOKUP_OBJECT (modification, entry7, "entry7");
  GLADE_HOOKUP_OBJECT (modification, entry8, "entry8");
  GLADE_HOOKUP_OBJECT (modification, label19, "label19");
  GLADE_HOOKUP_OBJECT (modification, label20, "label20");
  GLADE_HOOKUP_OBJECT (modification, label21, "label21");
  GLADE_HOOKUP_OBJECT (modification, label22, "label22");
  GLADE_HOOKUP_OBJECT (modification, label26, "label26");
  GLADE_HOOKUP_OBJECT (modification, valid_modif, "valid_modif");
  GLADE_HOOKUP_OBJECT (modification, alignment10, "alignment10");
  GLADE_HOOKUP_OBJECT (modification, hbox10, "hbox10");
  GLADE_HOOKUP_OBJECT (modification, image10, "image10");
  GLADE_HOOKUP_OBJECT (modification, label23, "label23");
  GLADE_HOOKUP_OBJECT (modification, modifier, "modifier");
  GLADE_HOOKUP_OBJECT (modification, alignment11, "alignment11");
  GLADE_HOOKUP_OBJECT (modification, hbox11, "hbox11");
  GLADE_HOOKUP_OBJECT (modification, image11, "image11");
  GLADE_HOOKUP_OBJECT (modification, label24, "label24");
  GLADE_HOOKUP_OBJECT (modification, radiobutton4, "radiobutton4");
  GLADE_HOOKUP_OBJECT (modification, radiobutton5, "radiobutton5");
  GLADE_HOOKUP_OBJECT (modification, checkbutton4, "checkbutton4");
  GLADE_HOOKUP_OBJECT (modification, checkbutton3, "checkbutton3");
  GLADE_HOOKUP_OBJECT (modification, retour_modif, "retour_modif");
  GLADE_HOOKUP_OBJECT (modification, alignment12, "alignment12");
  GLADE_HOOKUP_OBJECT (modification, hbox12, "hbox12");
  GLADE_HOOKUP_OBJECT (modification, image12, "image12");
  GLADE_HOOKUP_OBJECT (modification, label25, "label25");

  return modification;
}

GtkWidget*
create_cptdef (void)
{
  GtkWidget *cptdef;
  GtkWidget *fixed5;
  GtkWidget *treeview2;
  GtkWidget *button5;
  GtkWidget *alignment15;
  GtkWidget *hbox15;
  GtkWidget *image16;
  GtkWidget *label40;

  cptdef = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (cptdef), _("cptdef"));

  fixed5 = gtk_fixed_new ();
  gtk_widget_show (fixed5);
  gtk_container_add (GTK_CONTAINER (cptdef), fixed5);

  treeview2 = gtk_tree_view_new ();
  gtk_widget_show (treeview2);
  gtk_fixed_put (GTK_FIXED (fixed5), treeview2, 80, 80);
  gtk_widget_set_size_request (treeview2, 608, 328);

  button5 = gtk_button_new ();
  gtk_widget_show (button5);
  gtk_fixed_put (GTK_FIXED (fixed5), button5, 608, 432);
  gtk_widget_set_size_request (button5, 66, 29);

  alignment15 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment15);
  gtk_container_add (GTK_CONTAINER (button5), alignment15);

  hbox15 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox15);
  gtk_container_add (GTK_CONTAINER (alignment15), hbox15);

  image16 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image16);
  gtk_box_pack_start (GTK_BOX (hbox15), image16, FALSE, FALSE, 0);

  label40 = gtk_label_new_with_mnemonic (_("Rtour"));
  gtk_widget_show (label40);
  gtk_box_pack_start (GTK_BOX (hbox15), label40, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) button5, "clicked",
                    G_CALLBACK (on_retourcptdef_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (cptdef, cptdef, "cptdef");
  GLADE_HOOKUP_OBJECT (cptdef, fixed5, "fixed5");
  GLADE_HOOKUP_OBJECT (cptdef, treeview2, "treeview2");
  GLADE_HOOKUP_OBJECT (cptdef, button5, "button5");
  GLADE_HOOKUP_OBJECT (cptdef, alignment15, "alignment15");
  GLADE_HOOKUP_OBJECT (cptdef, hbox15, "hbox15");
  GLADE_HOOKUP_OBJECT (cptdef, image16, "image16");
  GLADE_HOOKUP_OBJECT (cptdef, label40, "label40");

  return cptdef;
}

